### ISSUE TITLE
[Crash] Widgets crash the app

### ISSUE THREAD

**Issue by ildar** [thuryn/your-local-weather#2] opened 2018-01-15 19:02 UTC
Just creating any widget crashes the app

**Comment by thuryn** [comment] 2018-01-15 21:21
Could you, please, describe me your phone brand and model and android version? Does app crash with all 3 kind of widgets? Is it possible to start main app and see weather?
Thank you for reporting.

**Comment by ildar** [comment] 2018-01-15 23:04
This installations from F-Droid. I've two Android 6 installations both
crashing.
Logcat is giving the clue:
> AndroidRuntime: java.lang.RuntimeException: Unable to start receiver
org.thosp.yourlocalweather.widget.ExtLocationWidgetProvider:
java.lang.ClassCastException: android.app.ReceiverRestrictedContext cannot
be
cast to android.app.Activity

**Comment by thuryn** [comment] 2018-01-16 09:05
Thank you for the response, I'll try to reproduce it on Android 6 (I've tested Android 4, 5, 7, 8 on emulator, so I'll try to reproduce the problem on Android 6). The whole exception stack from logcat would be helpful too.
Thank you for reporting.

**Comment by ildar** [comment] 2018-01-16 09:25
[adb-logcat.txt](https://github.com/thuryn/your-local-weather/files/1634344/adb-logcat.txt)

**Comment by thuryn** [comment] 2018-01-16 13:10
Thank you. I can guess what the problem is right now. I'll fix it, but you can try this workaround:
- open the main app (no widget)
- app should ask you for permissions - allow both of them

You can try to add widget right now.

**Comment by ildar** [comment] 2018-01-16 13:23
Yep, it worked.

**Comment by thuryn** [comment] 2018-01-16 22:28
Fixed in version 1.7

**Closed by thuryn** 2018-01-16 22:28 UTC
