### ISSUE TITLE
Impossible to add city manually

### ISSUE THREAD

**Issue by Zoldiru** [thuryn/your-local-weather#120] opened 2019-04-20 20:51 UTC
On Android 4.4.4, I cannot add city manually, nothing happens when I touch the add button.

**Comment by sm4rk0** [comment] 2019-04-22 16:02
Do you already have one location added? If so, it's duplicate of #113.

**Comment by Zoldiru** [comment] 2019-04-23 08:57
No, I don't have any location added yet.

**Comment by thuryn** [comment] 2019-05-04 14:57
I can confirm this bug. It seams that FloatingActionButton does not work on Android 4 at all. I'll move this action into action bar for Android 4. Sorry for this inconvenience.

**Comment by thuryn** [comment] 2019-05-17 14:39
it's fixed already

**Closed by thuryn** 2019-05-17 14:39 UTC
