### ISSUE TITLE
YLW doesn't update

### ISSUE THREAD

**Issue by ildar** [thuryn/your-local-weather#64] opened 2018-06-26 05:06 UTC
with my settings, see screenshots.

[log-yourlocalweather.txt](https://github.com/thuryn/your-local-weather/files/2135630/log-yourlocalweather.txt)
![screenshot_2018-06-26-06-36-18](https://user-images.githubusercontent.com/517752/41890103-d0394cd0-792f-11e8-9a44-4b4b72ffc1f6.png)
![screenshot_2018-06-26-06-36-34](https://user-images.githubusercontent.com/517752/41890105-d226c9fa-792f-11e8-8b28-ebc2bdacf7aa.png)

**Comment by AeliusSaionji** [comment] 2018-08-15 21:52
Mine has stopped auto updating as well!

**Comment by EDavidF** [comment] 2018-09-03 16:29
Having same issue. Android AOSP 8.1. Thanks for your work on this.

**Comment by oriold** [comment] 2018-09-05 09:14
LineageOS 15.1. Stopped working at no special time.
[log-yourlocalweather.txt](https://github.com/thuryn/your-local-weather/files/2352082/log-yourlocalweather.txt)

**Comment by thuryn** [comment] 2018-09-07 10:14
HI @oriold , thank you for the log. Is it possible that this problem starts when you upgraded xposed framework? The exception leads to the xposed framework.

**Comment by ghtux** [comment] 2018-09-18 08:36
Not updating here too. Los 15.1, no xposed

**Comment by thuryn** [comment] 2018-09-18 08:56
I've finally found where the problem is (one guy helped me by logs and screenshots from his phone). I've just made the changes (rewritten the logic) and I'm testing the solution right now. The problem affects update of locations and notifications also. Stay tuned for the next version (4.2.0). I'm really sorry for the inconvenience.

**Comment by ghtux** [comment] 2018-09-18 09:02
No need to apologize. Thanks for providing the app!

**Comment by thuryn** [comment] 2018-09-26 07:47
do the updates work starting 4.2.0 version?

**Comment by ghtux** [comment] 2018-09-26 07:53
Yes works after updating once manually.

**Comment by ghtux** [comment] 2018-10-02 16:28
Something is strange. Log message:

Background execution not allowed: receiving Intent { act=org.thosp.yourlocalweather.action.WEATHER_UPDATE_RESULT flg=0x10 (has extras) } to org.thosp.yourlocalweather/.widget.WeatherForecastWidgetProvider

**Comment by oriold** [comment] 2018-10-03 11:33
> Ups, yes, I forgot to update it. I did updated it and for now keeps failing to register. I will try to run without it.

forgot to update, but is working for me now. Regards,

**Comment by ghtux** [comment] 2018-10-07 13:39
Relax and recover! Hopefully no serious injuries?!

**Comment by thuryn** [comment] 2018-10-13 08:43
Thank you, I have a small injury on in my left knee (and I cannot step on the left leg for 8 weeks) and one serious injury of my right thumb (the thumb is broken till the joint), but it´s fixed now (there is metal plate inside the  thumb to harden the broken bone).

**Comment by sniperle** [comment] 2018-10-23 14:04
Still no automatic update for me with Version 4.3.1 from F-Droid on newest LineageOS 15.1
Tried reinstalling the App, but no success.

See the attached log please: [logcat_ylw.txt](https://github.com/thuryn/your-local-weather/files/2506412/logcat_ylw.txt)

**Comment by thuryn** [comment] 2018-10-23 15:33
> Still no automatic update for me with Version 4.3.1 from F-Droid on newest LineageOS 15.1
> Tried reinstalling the App, but no success.
> 
> See the attached log please: [logcat_ylw.txt](https://github.com/thuryn/your-local-weather/files/2506412/logcat_ylw.txt)

Really interesting, thank you for the log. Could you, please, try this build with several fixies regarding the exception in your log: https://de-next.owncube.com/index.php/s/ByGmG5XBWDD5ri3

**Comment by sniperle** [comment] 2018-10-23 15:50
Thanks for your quick answer. Downloaded your test built and installed it. Will report back after a short test.

**Comment by sniperle** [comment] 2018-10-23 20:16
At first it seemed like there is no difference, but after reading this article (https://stackoverflow.com/questions/44484937/android-o-limits-for-lower-target-sdk) I turned off battery optimisation for your fixed App and oh-wonder - now it works. ;-)

![20181023-ylw-batt](https://user-images.githubusercontent.com/3104188/47387868-22494880-d700-11e8-897a-e1cea8eace53.png)

**Comment by Nexion** [comment] 2018-10-24 09:22
@sniperle aww thanks for the advice. I've disabled the battery optimisation and finally the reload button (↻) on the widget is working on my stock Android 8.1. Unfortunately there are still no scheduled weather updates. Moreover, the 'Update period for weather' is greyed out in the settings though it was active before despite having no impact on the app behavior. I had even set it to '15 minutes' and it still shows it, but I can't change it anymore.

@thuryn is there a chance your recent build can make it work in my case or should I better provide my own log?

**Comment by sniperle** [comment] 2018-10-24 10:20
@Nexion 
Did you only try it with the standard app (from F-Droid or Google Play) or additionally with the "fixed" app? 
For me it is only working with the "fixed" app version from the link above.

**Comment by Nexion** [comment] 2018-10-24 10:55
@sniperle i'm using the 'standard' 4.2.6 release from F-Droid repository.

**Comment by Nexion** [comment] 2018-10-24 11:10
By the way, I was wrong — the app is successfully updating the weather data now every 15 minutes. I can't just change the update period because the setting is grayed out, but that I don't care much of.
Thanks for your work @thuryn

**Comment by thuryn** [comment] 2018-10-24 12:28
I'm going to create new dialog and ask user to disable battery optimization on Oreos and up. I've found it is possible.
@Nexion there are two options for time selection - for location 0 and for others. If combo for others is grayed out you don't have any location except the location 0 I suppose.

**Comment by Nexion** [comment] 2018-10-24 13:12
@thuryn now I see, thanks!

**Comment by ghtux** [comment] 2018-11-08 18:19
4.42 working again! But now widget is switching to location although it's deactivated per options. 😵

**Comment by ghtux** [comment] 2018-11-14 06:39
Seems my problem is flight mode related too. Updates stopped after switching to flight mode and back

**Comment by ghtux** [comment] 2018-11-16 06:01
V 4.4.4 and no more issues! Thanks thuryn!

**Comment by thuryn** [comment] 2018-11-18 14:53
when some specific problems arise open new issue, please

**Closed by thuryn** 2018-11-18 14:53 UTC
Labels: bug
