### ISSUE TITLE
Doesn't work whilst using approximate location

### ISSUE THREAD

**Issue by Victor239** [thuryn/your-local-weather#185] opened 2022-09-15 11:28 UTC
Newer Android differentiates between precise and approximate location as a permission. For some reason YLW doesn't work using approximate location currently.

**Comment by thuryn** [comment] 2022-09-25 13:50
Cannot reproduce this on A13. Are you able to provide log of the application?

**Comment by Victor239** [comment] 2022-09-25 23:07
Sure. What app should I use to log? This is on A12 btw.

**Comment by thuryn** [comment] 2022-09-26 07:15
First, in YLW menu Settings/Debug options and Log to file option. You can send me the file. But accept the fact, there are private information in the log (like BTS stattions etc.).
Second, when the app crashes you can send me logcat (adb logcat)

**Comment by thuryn** [comment] 2023-02-23 20:08
fixed in v5.8.15

**Closed by thuryn** 2023-02-23 20:08 UTC
