### ISSUE TITLE
Widget update error

### ISSUE THREAD

**Issue by linsui** [thuryn/your-local-weather#80] opened 2018-10-17 04:51 UTC
When I update the weather in the main app, the widget shows Location not found. It will not show the correct location and weather until I click the update button on the widget.

ROM: PixelExperience Android 9

**Comment by thuryn** [comment] 2018-10-25 06:36
Could you, please, try the 4.3.4 version - there are really important feature to get it to work on Oreo - the Pie needs this also.

**Comment by linsui** [comment] 2018-10-26 13:14
I have test 4.3.4. The widget still needs tobe updated manually.

**Comment by linsui** [comment] 2018-10-28 03:59
Sure. How can I get log file? I can't enable the log to file option. But the main app can update automatically now.

**Comment by thuryn** [comment] 2018-10-28 14:01
That's strange that logging is not possible to switch on. So the check box for file logging is not possible to check? First attampt to check this option just ask you for permission, the second attempt to check it makes the change.

Regards,
Tomas

28. října 2018 4:59:14 SEČ, linsui <notifications@github.com> napsal:

**Comment by thuryn** [comment] 2018-10-29 08:06
Perfect, now I know what the problem is - I'm going to fix it. Thank you a
lot.

po 29. 10. 2018 v 5:22 odesílatel linsui <notifications@github.com> napsal:

**Comment by linsui** [comment] 2018-11-08 10:41
The widget works well now，thanks. :joy: But sometimes I can't update the main app. It says an error occorred, try later.
[log-yourlocalweather.txt](https://github.com/thuryn/your-local-weather/files/2561349/log-yourlocalweather.txt)

**Comment by linsui** [comment] 2018-11-09 04:54
The widget can't show temperature.
![screenshot_20181109-124756](https://user-images.githubusercontent.com/36977733/48244036-6cc80600-e41e-11e8-8a7f-6d21cb446605.png)
[log-yourlocalweather.txt](https://github.com/thuryn/your-local-weather/files/2564644/log-yourlocalweather.txt)

**Comment by ildar** [comment] 2018-11-09 06:00
@linsui , on your screenshot, this looks like a very different issue, you
should open a new one for that. BTW, try resizing the widget.

**Comment by linsui** [comment] 2018-11-09 10:43
Sure.

**Comment by thuryn** [comment] 2018-11-18 14:54
I'm closing this issues - hopefully solved by v 4.4.5. If some problems arise open the issue please

**Closed by thuryn** 2018-11-18 14:54 UTC
