### ISSUE TITLE
Make my phone crash and the wigdet doesn't display correctly

### ISSUE THREAD

**Issue by mapsmak353478** [thuryn/your-local-weather#177] opened 2021-03-26 01:16 UTC
Hi, thanks for this great application

Version: 5.7.3
Pixel 5 with GrapheneOS

The application works, however it makes my phone crash (I have to uninstall it before my phone freezes)

The wigdet keeps trying to sync the weather and the icons are not displayed correctly.

I don't have this problem on a Pixel 3XL (with GapheneOS)
I have the same problem with a Oneplus 5T (with LineageOS 17.1)

![localweahter bug](https://user-images.githubusercontent.com/72702025/112563194-2ac67180-8dd9-11eb-93e8-d191031a7aab.jpg)

**Comment by thuryn** [comment] 2023-02-23 20:12
I know it's a lot of time. But still, does it work with the newest version? I've never seen this problem.

**Comment by nu111** [comment] 2023-02-27 19:44
I have a similar issue with Google Pixel 4a (stock android). The app is updated to the latest f-droid version, it always worked well, since (maybe) 3 version ago, the 4x1 widget with the daily weather forecast, is replaced with just black color.
![Screenshot_20230227-203649](https://user-images.githubusercontent.com/1246989/221666603-d07848f3-3495-49b8-9110-5cc754898b4d.png)

**Comment by thuryn** [comment] 2023-02-28 08:47
And does it work on the current version?

**Comment by nu111** [comment] 2023-02-28 09:05
Hi!

> And does it work on the current version?

I have update to the latest F-Droid version: 5.8.17, nope, doesn't work.

**Comment by thuryn** [comment] 2023-03-02 20:00
I've found it, fixed in version 5.8.18

**Closed by thuryn** 2023-03-02 20:00 UTC

**Comment by nu111** [comment] 2023-03-12 10:40
Today via F-Droid I updated to 5.8.19, I confirm that the issue is fixed, thanks!
