### ISSUE TITLE
Can't add more than 1 location

### ISSUE THREAD

**Issue by cabroncito** [thuryn/your-local-weather#113] opened 2019-01-14 09:55 UTC
Don't know if it's a bug, or a missing feature, or I am doing something wrong. I read here that it's possible to have 3 locations. I have GPS location disabled and it seems like I can only add 1 additional location. Would you help me, please?

Screenshot: 1 manual location, no red + button visible.
![screenshot_20190114-104506_](https://user-images.githubusercontent.com/46671578/51105891-94ef2f00-17ea-11e9-9f88-d5d348bd8c08.png)

**Comment by sm4rk0** [comment] 2019-01-14 12:03
Duplicate of #93 
Here's the maintainer's response: 
> This is not the bug, it's a feature. The reason for limit of 2 locations is in fact, that app access openweathermap.org with API key with limited number of connections. I'm working on some solution to provider commercial access to openweathermap.org - it's going to be paid.
> Sorry for inconvenience.

**Comment by cabroncito** [comment] 2019-01-14 19:49
Ah, I see. Sorry for double reporting. I only found issue [#43](https://github.com/thuryn/your-local-weather/issues/43) which states 3 locations. In any case, my "first location" (GPS) is deactivated. Hence, it should be possible to add another location manually without surpassing 2 locations in total... right?

**Comment by thuryn** [comment] 2019-02-25 16:09
it's fixed already. Does it work for you?

**Comment by cabroncito** [comment] 2019-03-08 22:14
Awesome, works splendidly! Thank you very much!

**Closed** 2019-03-08 22:54 UTC
